version: '2'

services:
  rabbitmq:
    restart: always
    container_name: rabbitmq
    image: rabbitmq:3.6.2-management
    environment:
      - RABBITMQ_DEFAULT_USER=muon
      - RABBITMQ_DEFAULT_PASS=microservices
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    networks:
        - default
        - muon

  photon:
    image: simplicityitself-muon-image.jfrog.io/photon:2017.10
    environment:
      - MUON_URL=amqp://muon:microservices@rabbitmq
    links:
      - rabbitmq
    ports:
      - "3000:3000"
      - "3500:3500"
    expose:
      - "3000"
      - "3500"
    command: -h2.path /data/muon/data.h2 -ui.port 3500 -rest.host 0.0.0.0
    networks:
        - default
        - muon

  gateway:
    restart: always
    image: simplicityitself-muon-image.jfrog.io/muonjs-gateway:latest
    environment:
      - MUON_URL=amqp://muon:microservices@rabbitmq
    links:
      - rabbitmq
    ports:
      - "9898:9898"
    networks:
        - default
        - muon

networks:
    muon:
      external: true
