rabbitmq:
  restart: always
  container_name: rabbitmq
  image: rabbitmq:3.5.4-management
  ports:
    - "15672:15672"
    - "5672:5672"
  environment:
    - RABBITMQ_DEFAULT_USER=muon
    - RABBITMQ_DEFAULT_PASS=microservices
infra-link:
  restart: always
  image: quay.io/simplicityitself/infra-docker-compose
  links:
    - rabbitmq
  privileged: true
  volumes:
    - ../:/applocal/environments 
    - /var/run/docker.sock:/container/path/docker.sock
